import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@myapp/react";

const Home: NextPage = () => {
  const dogsQuery = trpc.useQuery(["getDogs"]);

  return (
    <div>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, world!</h1>
      {dogsQuery.data?.map((dog) => (
        <div key={dog.name}>
          {dog.name} {dog.goodBoy ? "is" : "IS NOT"} a good boy.
        </div>
      ))}
    </div>
  );
};

export default Home;
