import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@myapp/react";

const Home: NextPage = () => {
  const dogsQuery = trpc.useQuery(["getDogs"]);

  return (
    <div className="p-3">
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl text-primary">My dogs!</h1>
      <ul className="p-3 list-disc">
        {dogsQuery.data?.map((dog) => (
          <li key={dog.name}>
            {dog.name}{" "}
            <span className={dog.goodBoy ? "text-green-700" : "text-red-700"}>
              {dog.goodBoy ? "is" : "IS NOT"}
            </span>{" "}
            a good boy.
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
