import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@myapp/react";

const Home: NextPage = () => {
  const [title, setTitle] = React.useState("");

  const { getQueryData, setQueryData, invalidateQueries } = trpc.useContext();
  const todosQuery = trpc.useQuery(["getTodos"]);
  const addTodo = trpc.useMutation(["addTodo"], {
    onSuccess: (res) => {
      const prevTodos = getQueryData(["getTodos"]) || [];
      setQueryData(["getTodos"], [...prevTodos, res]);
    },
    onSettled: () => {
      invalidateQueries(["getTodos"]);
    },
  });

  return (
    <div className="p-3">
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl text-primary">My TODOs.</h1>
      <ul className="p-3 list-disc">
        {todosQuery.data?.map((item) => (
          <li key={item.id}>
            "{item.title}"{" "}
            <span
              className={item.isComplete ? "text-green-700" : "text-red-700"}
            >
              {item.isComplete ? "is" : "IS NOT"}
            </span>{" "}
            complete
          </li>
        ))}
      </ul>

      <div>
        <h1 className="text-3xl">Add an item</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            addTodo.mutate({ title: title });
            setTitle("");
          }}
        >
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.currentTarget.value)}
          />
          <button>Submit</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
